image:
- Visual Studio 2017

hosts:
  api.nuget.org: 93.184.221.200

before_build:
- dotnet restore

build_script:
- dotnet build -c Release

test_script:
- dotnet test .\Bonus.Immutable.Test\Bonus.Immutable.Test.csproj

after_test:
- dotnet pack .\Bonus.Immutable -c Release --include-symbols

artifacts:
- path: '**\*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: gyCXGF2/UBV/XLtvg6Iz/Acrbwghdh/SNapM1449YL2SJhzeK0ZKLgQOt6h/q8Uh
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
